### PR TITLE
Reformat 'changelog.txt' to markdown

### PR DESCRIPTION
**Pull request by thomasduchatelet**

### CODE REVIEW

**Comment by cogitantium** [comment]
Hi @thomasduchatelet, thanks for the PR - I've changed target branch to `dev`, and as such the unreleased part of the changelog is missing. If you'd like, you're welcome to revise your PR by pushing further commits to your own branch; `thomasduchatelet:master`.

**Comment by thomasduchatelet** [comment]
I guess it better now? Sorry i'm new around here and not yet confident with all of github's features

**Comment by NicEastvillage** [comment]
Hi @thomasduchatelet, good work. Just one more thing. We would like your branch to be merged into the `dev` branch, but because to branch out from `master`, there will be conflicts. Do you know how to resolve merge conflicts?

**Comment by thomasduchatelet** [comment]
> Hi @thomasduchatelet, good work. Just one more thing. We would like your branch to be merged into the `dev` branch, but because you originally branch out from `master`, there will be conflicts. Do you know how to resolve merge conflicts?

Actually no :/

**Comment by cogitantium** [comment]
@thomasduchatelet, I hope you're interested. It's not too difficult and this specific PR is a good place to learn it, as it's a simple change and you've got us two, to help you. Let us know if you're up for it!

**Comment by cogitantium** [comment]
PR #41 fixes the issues that this PR aims to fix. Closing this PR.

**Pull request closed without merging**
