### PR TITLE
Upgrading to Java 11, setting up MSI installer.

### PR DESCRIPTION
**Pull request by tarehart**
This allows you to vend a MSI installer which does not require the user to have Java installed at any point. This is nice because even when people do install Java these days, it tends to be Java 11 which lacks javafx and does not support cleopetra.

Currently the installer is pretty goofy, it does not give any kind of success message, but it does at least place a shortcut on the desktop. I end up with C:\Program Files\cleopetra\cleopetra.exe.

I can send the msi for testing upon request.

I was obliged to change the folder structure because the new gradle plugins were very unhappy with the current non-standard layout.

### CODE REVIEW

**Comment by NicEastvillage** [comment]
Thank you, tarehart. This will be a great change. I would like test the installer.

**Comment by NicEastvillage** [comment]
Works like a charm!

Now for completeness:
* We already have an icon for cleo. It can be found at `cleopetra/src/dk/aau/cs/ds306e18/tournament/ui/layout/images/logo.png`. Let me know if you need another file type.
* The msi installer says `1.0` but the current version is `1.7.3` (soon 1.7.4) as seen in `changelog.md`.
* Feel like free to add the change to `changelog.md`

**Comment by tarehart** [comment]
Well that was easier than I expected! Has an icon now, and also you can double click any rlts file and it will open cleopetra and bypass the "new / open" launcher view.

**Review by NicEastvillage — APPROVED** [review]
This jpackage stuff is absolute magic.

**Pull request merged**
